services:
  mysql:
    image: mysql:8.0
    container_name: hungry_hare_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hungry_hare
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: hungry_hare_backend
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: hungry_hare

  frontend:
    build: ./frontend
    container_name: hungry_hare_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: